// <auto-generated />
using System;
using LuxuryCo.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuxuryCo.Database.Migrations
{
    [DbContext(typeof(LuxuryCoDbContext))]
    [Migration("20260313124709_AddCatalogoSeed")]
    partial class AddCatalogoSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuxuryCo.Database.Models.Carrito", b =>
                {
                    b.Property<int>("id_carrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carrito"));

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_carrito");

                    b.HasIndex("id_usuario");

                    b.ToTable("carrito", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_categoria");

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            id_categoria = 1,
                            descripcion = "Productos para hombre",
                            nombre = "Hombre"
                        },
                        new
                        {
                            id_categoria = 2,
                            descripcion = "Productos para mujer",
                            nombre = "Mujer"
                        },
                        new
                        {
                            id_categoria = 3,
                            descripcion = "Accesorios en general",
                            nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Ciudad", b =>
                {
                    b.Property<int>("id_ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_ciudad"));

                    b.Property<int?>("id_departamento")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_ciudad");

                    b.HasIndex("id_departamento");

                    b.ToTable("ciudad", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Departamento", b =>
                {
                    b.Property<int>("id_departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_departamento"));

                    b.Property<string>("nombre_departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_departamento");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.DetalleCarrito", b =>
                {
                    b.Property<int>("id_detalle_carrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_detalle_carrito"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("id_carrito")
                        .HasColumnType("integer");

                    b.Property<int?>("id_producto")
                        .HasColumnType("integer");

                    b.HasKey("id_detalle_carrito");

                    b.HasIndex("id_carrito");

                    b.HasIndex("id_producto");

                    b.ToTable("detalle_carrito", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.DetallePedido", b =>
                {
                    b.Property<int>("id_detalle_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_detalle_pedido"));

                    b.Property<int?>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("id_pedido")
                        .HasColumnType("integer");

                    b.Property<int?>("id_producto")
                        .HasColumnType("integer");

                    b.Property<decimal?>("precio_unitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id_detalle_pedido");

                    b.HasIndex("id_pedido");

                    b.HasIndex("id_producto");

                    b.ToTable("detalle_pedido", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.DireccionUsuario", b =>
                {
                    b.Property<int>("id_direccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_direccion"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("id_ciudad")
                        .HasColumnType("integer");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("referencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("id_direccion");

                    b.HasIndex("id_ciudad");

                    b.HasIndex("id_usuario");

                    b.ToTable("direccion_usuario", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Envio", b =>
                {
                    b.Property<int>("id_envio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_envio"));

                    b.Property<DateTime?>("fecha_envio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("id_estado_envio")
                        .HasColumnType("integer");

                    b.Property<int?>("id_pedido")
                        .HasColumnType("integer");

                    b.Property<string>("numero_guia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_envio");

                    b.HasIndex("id_estado_envio");

                    b.HasIndex("id_pedido")
                        .IsUnique();

                    b.ToTable("envio", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.EstadoEnvio", b =>
                {
                    b.Property<int>("id_estado_envio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_estado_envio"));

                    b.Property<string>("nombre_estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id_estado_envio");

                    b.ToTable("estado_envio", (string)null);

                    b.HasData(
                        new
                        {
                            id_estado_envio = 1,
                            nombre_estado = "Preparando"
                        },
                        new
                        {
                            id_estado_envio = 2,
                            nombre_estado = "En camino"
                        },
                        new
                        {
                            id_estado_envio = 3,
                            nombre_estado = "Entregado"
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.EstadoPedido", b =>
                {
                    b.Property<int>("id_estado_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_estado_pedido"));

                    b.Property<string>("nombre_estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id_estado_pedido");

                    b.ToTable("estado_pedido", (string)null);

                    b.HasData(
                        new
                        {
                            id_estado_pedido = 1,
                            nombre_estado = "Pendiente"
                        },
                        new
                        {
                            id_estado_pedido = 2,
                            nombre_estado = "Pagado"
                        },
                        new
                        {
                            id_estado_pedido = 3,
                            nombre_estado = "Enviado"
                        },
                        new
                        {
                            id_estado_pedido = 4,
                            nombre_estado = "Cancelado"
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Factura", b =>
                {
                    b.Property<int>("id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_factura"));

                    b.Property<DateTime>("fecha_factura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("id_metodo_pago")
                        .HasColumnType("integer");

                    b.Property<int?>("id_pedido")
                        .HasColumnType("integer");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id_factura");

                    b.HasIndex("id_metodo_pago");

                    b.HasIndex("id_pedido")
                        .IsUnique();

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.ImagenProducto", b =>
                {
                    b.Property<int>("id_imagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_imagen"));

                    b.Property<int?>("id_producto")
                        .HasColumnType("integer");

                    b.Property<bool>("principal")
                        .HasColumnType("boolean");

                    b.Property<string>("url_imagen")
                        .HasColumnType("text");

                    b.HasKey("id_imagen");

                    b.HasIndex("id_producto");

                    b.ToTable("imagen_producto", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Marca", b =>
                {
                    b.Property<int>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_marca"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("logo_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_marca");

                    b.ToTable("marca", (string)null);

                    b.HasData(
                        new
                        {
                            id_marca = 1,
                            logo_url = "",
                            nombre = "MONEY MAKERS"
                        },
                        new
                        {
                            id_marca = 2,
                            logo_url = "",
                            nombre = "Y/OUT"
                        },
                        new
                        {
                            id_marca = 3,
                            logo_url = "",
                            nombre = "BLOW UP"
                        },
                        new
                        {
                            id_marca = 4,
                            logo_url = "",
                            nombre = "CULTUREWISE"
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.MetodoPago", b =>
                {
                    b.Property<int>("id_metodo_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_metodo_pago"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id_metodo_pago");

                    b.ToTable("metodo_pago", (string)null);

                    b.HasData(
                        new
                        {
                            id_metodo_pago = 1,
                            descripcion = "Pago con tarjeta",
                            nombre = "Tarjeta"
                        },
                        new
                        {
                            id_metodo_pago = 2,
                            descripcion = "Pago por PSE",
                            nombre = "PSE"
                        },
                        new
                        {
                            id_metodo_pago = 3,
                            descripcion = "Pago por Nequi",
                            nombre = "Nequi"
                        },
                        new
                        {
                            id_metodo_pago = 4,
                            descripcion = "Pago contra entrega",
                            nombre = "Contra entrega"
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Pedido", b =>
                {
                    b.Property<int>("id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_pedido"));

                    b.Property<DateTime>("fecha_pedido")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("id_direccion")
                        .HasColumnType("integer");

                    b.Property<int?>("id_estado_pedido")
                        .HasColumnType("integer");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id_pedido");

                    b.HasIndex("id_direccion");

                    b.HasIndex("id_estado_pedido");

                    b.HasIndex("id_usuario");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Producto", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_producto"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("id_categoria")
                        .HasColumnType("integer");

                    b.Property<int?>("id_marca")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("stock")
                        .HasColumnType("integer");

                    b.HasKey("id_producto");

                    b.HasIndex("id_categoria");

                    b.HasIndex("id_marca");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Resena", b =>
                {
                    b.Property<int>("id_resena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_resena"));

                    b.Property<int>("calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("id_producto")
                        .HasColumnType("integer");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_resena");

                    b.HasIndex("id_producto");

                    b.HasIndex("id_usuario");

                    b.ToTable("resena", (string)null);
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_rol"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id_rol");

                    b.ToTable("rol", (string)null);

                    b.HasData(
                        new
                        {
                            id_rol = 1,
                            descripcion = "Administrador del sistema",
                            nombre_rol = "ADMIN"
                        },
                        new
                        {
                            id_rol = 2,
                            descripcion = "Cliente regular",
                            nombre_rol = "CLIENTE"
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("foto_perfil_url")
                        .HasColumnType("text");

                    b.Property<int?>("id_rol")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("reset_password_code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("reset_password_expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("two_factor_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("two_factor_secret")
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_rol");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            id_usuario = 1,
                            activo = true,
                            apellido = "LuxuryCo",
                            email = "admin@luxuryco.com",
                            fecha_registro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            foto_perfil_url = "",
                            id_rol = 1,
                            nombre = "Admin",
                            password_hash = "TODO_HASH_THIS_Password123*",
                            telefono = "123456789",
                            two_factor_enabled = false,
                            two_factor_secret = ""
                        });
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Carrito", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Ciudad", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Departamento", "Departamento")
                        .WithMany("Ciudades")
                        .HasForeignKey("id_departamento");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.DetalleCarrito", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Carrito", "Carrito")
                        .WithMany("Detalles")
                        .HasForeignKey("id_carrito");

                    b.HasOne("LuxuryCo.Database.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("id_producto");

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.DetallePedido", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("id_pedido");

                    b.HasOne("LuxuryCo.Database.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("id_producto");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.DireccionUsuario", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("id_ciudad");

                    b.HasOne("LuxuryCo.Database.Models.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("id_usuario");

                    b.Navigation("Ciudad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Envio", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.EstadoEnvio", "EstadoEnvio")
                        .WithMany("Envios")
                        .HasForeignKey("id_estado_envio");

                    b.HasOne("LuxuryCo.Database.Models.Pedido", "Pedido")
                        .WithOne("Envio")
                        .HasForeignKey("LuxuryCo.Database.Models.Envio", "id_pedido");

                    b.Navigation("EstadoEnvio");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Factura", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.MetodoPago", "MetodoPago")
                        .WithMany("Facturas")
                        .HasForeignKey("id_metodo_pago");

                    b.HasOne("LuxuryCo.Database.Models.Pedido", "Pedido")
                        .WithOne("Factura")
                        .HasForeignKey("LuxuryCo.Database.Models.Factura", "id_pedido");

                    b.Navigation("MetodoPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.ImagenProducto", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("id_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Pedido", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.DireccionUsuario", "DireccionUsuario")
                        .WithMany()
                        .HasForeignKey("id_direccion");

                    b.HasOne("LuxuryCo.Database.Models.EstadoPedido", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("id_estado_pedido");

                    b.HasOne("LuxuryCo.Database.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("id_usuario");

                    b.Navigation("DireccionUsuario");

                    b.Navigation("EstadoPedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Producto", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("id_categoria");

                    b.HasOne("LuxuryCo.Database.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("id_marca");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Resena", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Producto", "Producto")
                        .WithMany("Resenas")
                        .HasForeignKey("id_producto");

                    b.HasOne("LuxuryCo.Database.Models.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("id_usuario");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Usuario", b =>
                {
                    b.HasOne("LuxuryCo.Database.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("id_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Carrito", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Departamento", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.EstadoEnvio", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.MetodoPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Envio");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Producto", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LuxuryCo.Database.Models.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Direcciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
